libraries/java/zyra.json
=> Adding java/zyra

libraries/elixir/godfist.json
=> Adds library to Elixir folder

libraries/typescript/league-typedef.json
This PR creates a Typescript folder and adds the repo league-typedef.
=> Adding league-typedef

libraries/typescript/zedgg.json
added json file in typescript folder for zed.gg
=> add zed gg in typescript folder

libraries/javascript/leaguejs1.json
- v3 rework
- published under "correct" name to npm (leaguejs)
=> Add LeagueJS rework

libraries/c-sharp/riotgamesapiaspnetcore.json
sync with master repo and PR created again but still failed.
is this metadata restriction ? @WxWatch 
EDIT: unnecessary comma caused a problem now it is ok. :)
=> rate-limiting and caching

libraries/php/riotapi.json
=> dolejska-daniel/riot-api updates

libraries/c-sharp/riotgamesapiaspnetcore.json
next, documentation will move to https://riotgamesapi.readme.io/
=> moved to main page

libraries/c-sharp/cottontailsummoners
This project contain an API V3 wrapper and a ASP.net website.
=> Add new library

libraries/swift/leagueapi.json
Adding leagueapi.json configuration file for new Swift framework LeagueAPI
=> new Swift framework LeagueAPI

libraries/typescript/jarvanscript.json
=> JarvanScript

libraries/javascript/riotapi-grab.json
TypeScript (javascript) API wrapper
=> Added riotapi-grab

libraries/c-sharp/camille.json
Also updating description & metadata
=> Update c#/camille.json for V4

libraries/javascript/kayn.json
=> Update kayn.json for v4

docs/DEVELOPERS, docs/applications.rst, docs/collectingdata.rst, docs/ddragon.rst, docs/esports.rst, docs/index.rst, docs/lcu.rst, docs/mobile.rst, docs/replayapi.rst, docs/roleid.rst, docs/specifics.rst
Many of the pages are not included in the index.rst file (they are "commented" out in the toctree) because they are unfinished, but they'll at least provide a baseline for adding more.
=> updated docs with some more stuff

libraries/php/riotquestv4.json
I added my newly created PHP framework for the Riot API.
=> Adding RiotQuest for PHP

libraries/php/riotquestv4.json
Edited some metadata and updated the documentation link.
=> Update PHP RiotQuest

libraries/go/golio.json
This is an API client I wrote, which currently supports the mastery, champion, league, status, match and summoner endpoints, as well as the data dragon service. It also handles rate limiting.
=> Golang api client: Golio

libraries/javascript/leagueapiwrapper.json
JavaScript APIWrapper 'MundoScript' (github) 'leagueapiwrapper' (NPM)
=> added leagueapiwrapper.json

libraries/php/riotquestv4.json
Updated the description and version tag for RiotQuest
=> Update riotquest description and version

libraries/julia/loltoolsjl.json
hi. I'd like to add a package for Julia language.
https://github.com/wookay/LOLTools.jl
=> Add julia loltoolsjl.json

libraries/go/golio.json
added caching capabilities, so I updated the tags to reflect that.
=> libraries/go/golio: update tags

libraries/python/django-cassiopeia.json
Updated the documentation url due because I've nuked readthedocs and shorten the descriptions for better fitting the bots command.
=> Updated url and description

libraries/javascript/fmgg-riot-api.json
https://github.com/fightmegg/riot-api
=> Add new Riot API client

libraries/c-sharp/mikaelduiriotgamesclient.json
... and added a comment about LCU.
=> Corrected typo in mikaelduiriotgamesclient.json

libraries/javascript/shieldbow.json, libraries/typescript/shieldbow.json
Adds [shieldbow](https://github.com/TheDrone7/shieldbow) config files in JavaScript and TypeScript folders.
=> Add shieldbow config

libraries/cpp/riot-cpp.json
Added my library riot-cpp and created a directory for cpp
=> added riot-cpp library

libraries/javascript/shieldbow.json, libraries/typescript/shieldbow.json
Shieldbow has 2 github links, yeet one of them
=> Remove redundant github link

libraries/c-sharp/riotblossom.json
=> Add RiotBlossom

libraries/php/malphphite.json
New php library ^^
Hope the JSON is conform to the schema
=> Add malPHPhite

libraries/cpp/rito.json
=> fix: rito repo name change
